### ISSUE TITLE
Minor UI glitch in boxes showing commits-per-week

### ISSUE THREAD

**Issue by spier** [SAP/project-portal-for-innersource#7] opened 2020-12-30 13:45 UTC
I spotted a minor UI glitch. The left-most box showing the commits-per-week is missing the outer-left border. See screenshot.

The screenshots in the README don't have that problem, so I suspect it is something that is dependent on my browser or similar?

![minor-ui-glitch-in-activity-boxes](https://user-images.githubusercontent.com/163029/103355043-8371c100-4aad-11eb-9d18-cce766a55d8a.JPG)

**Comment by Michadelic** [comment] 2021-01-21 08:24
I couldn't reproduce this on Chrome/Windows, which browser are you using?

**Comment by spier** [comment] 2021-01-21 08:31
I am on Chrome/OSX. However I just tested tested this again and the issue seems to be gone.
I may have updated Chrome in between, not 100% sure.

We can close the issue if you like, as I cannot provide reproduction steps.

**Comment by Michadelic** [comment] 2021-01-21 08:45
could be subpixel calculation rounding error in the browser. Usually the browser rounds borders to an integer but in your screenshot it seems like there is an aliasing in place. Closing the issue for now. If you spot it again, kindly reopen.

**Closed** 2021-01-22 08:40 UTC
